spring.application.name=Study_application
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/study_application_db?useSSL=false&serverTimezone=Asia/Seoul
# ?????? ?? ?? ??
spring.datasource.username=root
# ?????? ?? ????
spring.datasource.password=root

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sandrock0429@gmail.com
spring.mail.password=lslrffqsqgjaheov        
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=redis-11795.c283.us-east-1-4.ec2.redns.redis-cloud.com
spring.data.redis.port=11795
spring.data.redis.username=default
spring.data.redis.password=hmWVUCgTirF2ZlCuuRwVOhRqFvUa0ize